In [8]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
print(np.__version__)


[1 2 3 4 5]
2.3.2


In [4]:
#CREATING 2D ARRAY
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [7]:
#3D ARRAY IN NUMPPY
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [10]:
import numpy as np
a=np.array(42)
b=np.array([1,2,3,4,5])
c=np.array([[1,2,3],[4,5,6]])
d=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [13]:
#5D ARRAY IN NUMPY
import numpy as np
arr=np.array([1,2,3,4],ndmin=5)
print(arr)
print('number of dimensions:',arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions: 5


In [14]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('2nd element on 1st row:',arr[0,1])


2nd element on 1st row: 2


In [15]:
arr=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8


In [17]:
#JOINING TWO ARRAYS
##CONCATENATE
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.concatenate((arr1,arr2))

print(arr)

[1 2 3 4 5 6]


In [19]:
#ARRAY SEARCH
arr=np.array([1,2,3,4,5,4,4])
x=np.where(arr==7)
print(x)

(array([], dtype=int64),)


In [20]:
#SORTING THE ARRAY
arr=np.array([3,2,0,1])
print(np.sort(arr))

[0 1 2 3]


In [21]:
arr=np.array([41,42,43,44])
x=[True,False,True,False]
newarr=arr[x]
print(newarr)

[41 43]


In [3]:
#DICTIONARIES PROGRAM IN PYTHON
purse=dict()
purse['money']=12
purse['candy']=3
purse['tissues']=75
print(purse)
print(purse['candy'])
print(purse['money'])
purse['candy']=purse['candy']+2
print(purse)

{'money': 12, 'candy': 3, 'tissues': 75}
3
12
{'money': 12, 'candy': 5, 'tissues': 75}
